### ISSUE TITLE
A simple question you may have the answer for this.

### ISSUE THREAD

**Issue by SanjayYadav90** [grantchen/google_play_search#10]
Hi,

I know this is not related to this but ...

I just see some code of ruby, but unable to know its meanings, let me know 
---------------------------------------------------------
what is diff in 2+3 and 2.+(3) in ruby ?
what it mean, its use and importance?
----------------------------------------------------------
Hope for help.

**Comment by grantchen** [comment]
Hi @SanjayYadav90 

It seems no difference between them. Sorry, I don't use the code like this before.
