### ISSUE TITLE
bad URI(is not URI?): https://play.google.com/store/search?q=+Communication&c=apps&hl=en&price=0&rating=0&start=0&num=0&pagTok=d\\u003d:S:ANO1ljL7Yco

### ISSUE THREAD

**Issue by SanjayYadav90** [grantchen/google_play_search#11]
Hi,
There is a issue with my app search.
when I search more N numbers of  application then it generates one error as-

bad URI(is not URI?): https://play.google.com/store/search?q=+Communication&c=apps&hl=en&price=0&rating=0&start=0&num=0&pagTok=d\\u003d:S:ANO1ljL7Yco

Extracted source (around line #67):
65
66
67
68
69
70
              
      end
      #binding.pry
---------------------------------------
        @app = gps.next_page // here is the error
--------------------------------------
        break if !@app.present? #or p gps.current_page == 1
    end
	end

Rails.root: /home/sanjay/Project/AppseWorld

Application Trace | Framework Trace | Full Trace
app/models/app_manager.rb:67:in `block in getGPS'
app/models/app_manager.rb:6:in `loop'
app/models/app_manager.rb:6:in `getGPS'
app/controllers/home_controller.rb:15:in `index'

How to solve this issue.
Any help ?

**Comment by grantchen** [comment]
Hi @SanjayYadav90 

Test by below code, it works.
```ruby
apps = gps.search("Communication")
apps.map(&:id)
=> ["com.android.chrome", "com.popularapp.periodcalendar", "com.google.android.gm", "com.cyworld.camera", "com.ebay.mobile", "com.remind101", "org.mozilla.firefox", "com.sonyericsson.extras.liveware", "com.sonyericsson.xhs", "com.azarlive.android", "org.thoughtcrime.redphone", "com.dsi.ant.service.socket", "com.yuilop", "com.dsi.ant.plugins.antplus", "com.nhn.android.band", "com.trantrigroup.cauthongdung", "com.tencent.mobileqqi", "com.faadooengineers.free_satellitecommunications", "com.appsmoment.goodcomskills", "com.linecorp.lineat.android"]


new_apps = gps.next_page
 new_apps.map(&:id)
=> ["and.p2l", "net.one97.paytm", "com.icq.mobile.client", "com.rebelvox.voxer", "com.freephoo.android", "com.airelive.apps.choco", "com.wagmob.communicationpower", "com.hipchat", "com.masterandbull.tellmewhycommunication", "org.torproject.android", "com.evernote.skitch", "com.callapp.contacts", "ix.com.android.VirtualWalkieTalkie", "com.faadooengineers.free_datacommunicationandnetwork", "com.sony.mobile.ep", "mobi.drupe.app", "com.posora.businesscommunication", "it.csp.t4a.toolsforautism.tc_modello1", "com.trtf.blue", "com.visinor.phonewarrior"]
```

**Comment by grantchen** [comment]
@SanjayYadav90 if you found it happen again, please re-open it, Thanks.
