### ISSUE TITLE
How I can get more details of Google Apps by using this Gem.....

### ISSUE THREAD

**Issue by SanjayYadav90** [grantchen/google_play_search#7]
Hi, 

It really helpful and interesting. I am using it in my current app. 
I need complete detail  of the app like-

> Company Deail,
> Company Email,
> App snapshots,
> All reviews related to that app 

and much more.  I hope for your great support as soon as possible. 

Thanx.

**Comment by grantchen** [comment]
Hi @SanjayYadav90 

Current version can not  get these info.
Next version, i will try add it.

Thanks for your question.

**Comment by SanjayYadav90** [comment]
Hi grantchen,

Can you please let me know how to get Next Version of this Gem.
I really need this feature in my app.

You can also give me the url of new version and all the stuff.

Thanx for Reply.

**Comment by grantchen** [comment]
Hi SanjayYadav90 

I means next release version i will try add these info.

**Comment by grantchen** [comment]
Hi SanjayYadav

Please update latest version, you can get below info now.

# app developer website
app.developer_website

# app developer email
app.developer_email

# app developer address
app.developer_address

# app reviews (only 40 reviews)
app.reviews
#<GooglePlaySearch::Review
# @author_name="alex persohn",
# @author_avatar="https://lh6.googleusercontent.com/xxxxxxx/photo.jpg",
# @review_title="Was really fun, but keeps freezing.",
# @review_content="This is a really addicting game, but as of late the app keeps freezing. Every three games or so, it will freeze and I have to kill the app via task manager. It's some error in the app fetching the add, which just makes it even more frustrating. Would rate 5 stars if this didn't happen.",
# @star_rating= 1

**Comment by SanjayYadav90** [comment]
Wow great,

Its working fine. Its my pleasure.
Thanking you.

There is an issue with email, reviews, website and developer address:
email:-  sometime it gives correct email 
             sometime like "Privacy Policy"
             sometime like nil value.
address:    sometime like Required Data which we need.
                  sometime like nil values. and same with "Reviews"
Please review it and try to get it fixed to help me better.

------------------------------------------------------------

I also need screen shorts, so please help me to do so.

-------------------------------------------------------------
thankz

**Comment by SanjayYadav90** [comment]
how to find screenshot of the app.

and mail in appropriate format.

**Comment by grantchen** [comment]
Hi 

I have fixed some email wrong bug also add get screenshots feature. Please update gem to 0.0.15

**Comment by SanjayYadav90** [comment]
Hi,

I had already did the same which never gives me any bug, I have my own Parse for that.
Now I have all related data of particular app with me like Updated, Size, installs, Current Version,
Requires Android, Content Rating, Develper email, website, address etc.
If you want to see i can share that with you.

Thanking you.
