### ISSUE TITLE
Is it possible to get list of complete apps on a single page, if yes then how?

### ISSUE THREAD

**Issue by SanjayYadav90** [grantchen/google_play_search#8]
Hi,

It's working fine and stay very helpful for me, it was really nice experience with this gem.

Que:- Just I need complete list of apps with a single search, as we can find only 20 apps on each search, related to each category. I want all list of application without any limitation (how many it may be). 
else just let me know how to increase its limitation.

Hope to have a help soon.
Thanking you

Sanjay

**Comment by grantchen** [comment]
Hi, 

Sorry, it seems can not get complete list of apps. If you can not get complete list of apps by search app in    https://play.google.com/store site one time, the gem also can not implement it.

**Comment by SanjayYadav90** [comment]
Hi,

It nice to inform you that, I have did my task, GREAT

now i have complete list of applications which I asked you for.


have a nice day!!
