### ISSUE TITLE
How to get App's long description?

### ISSUE THREAD

**Issue by makuchaku** [grantchen/google_play_search#9]
app.short_description works but there is no method to fetch app.long_description.

Please do add that method.

Thanks!

**Comment by SanjayYadav90** [comment]
Hi makuchaku,

You can fetch only short_description, there is no method  to get app.long_description.
May grantchen (https://github.com/grantchen) may help you by updating the Gem.

Else You can create your own Parser for the same,

Thans

**Comment by grantchen** [comment]
Hi makuchaku

I have add app.long_description method.
Please update to 0.0.16 version.
